/* Agentic AI: six cooperating agents handle an incident, with a human approval gate. */
(function(){
'use strict';
var SX=window.SX;
var SCEN=SX.SCENARIOS={
 phishing:{name:'Phishing email',alert:'User opened a link in an invoice email and downloaded an attachment',sev:'high',base:62,q:'phishing malicious link credentials',cnn:'trojan',file:'invoice_2291.exe',mitre:'T1566',sum:'The attachment behaves like a trojan and the sender pattern matches phishing.',actions:['Quarantine the email from all mailboxes','Block the sender domain at the mail gateway','Revoke the user sessions and force a password reset']},
 ransom:{name:'Ransomware',alert:'Mass file renames with a new extension on workstation FIN-WS-07',sev:'crit',base:78,q:'ransomware encrypt files isolate',cnn:'ransomware',file:'locker.bin',mitre:'T1486',sum:'File behaviour and the binary both point to encryption for impact.',actions:['Isolate FIN-WS-07 from the network','Disable the affected user account','Snapshot the host for forensics','Verify the latest offline backup']},
 sqli:{name:'SQL injection',alert:'UNION SELECT strings in the id parameter of /api/orders',sev:'crit',base:74,q:'sql injection web logs',cnn:null,file:'',mitre:'T1190',sum:'The request pattern matches a known injection technique against a public endpoint.',actions:['Block the source address at the web application firewall','Enable a strict rule on /api/orders','Open a ticket to parameterize the query']},
 brute:{name:'Password spraying',alert:'480 failed logins across 12 accounts from one address in 3 minutes',sev:'high',base:58,q:'brute force password spraying',cnn:null,file:'',mitre:'T1110',sum:'One source is trying common passwords against many accounts.',actions:['Rate-limit and block the source address','Require multi-factor authentication on the targeted accounts','Notify the account owners']},
 beacon:{name:'Malware beaconing',alert:'Laptop DEV-LT-22 contacts a rare domain every 60 seconds',sev:'high',base:64,q:'command and control beaconing rare domain',cnn:'botnet',file:'svc-update.dll',mitre:'T1071',sum:'Regular timing and a templated binary suggest a bot in contact with its controller.',actions:['Sinkhole the domain in DNS','Isolate DEV-LT-22','Collect a memory image for analysis']},
 deepfake:{name:'Deepfake payment request',alert:'Finance received a voice call that sounds like the CEO asking for an urgent transfer',sev:'high',base:60,q:'deepfake voice social engineering payment',cnn:null,file:'',mitre:'T1566',sum:'The urgency, the bypass of normal approval and the refusal of a call-back match voice-clone fraud.',actions:['Hold the transfer and verify through a second channel','Alert the finance team about the attempt','Require two-person approval for all urgent transfers this week']}
};
var AGENTS=['Monitor','Planner','Analyst','Reasoner','Responder','Reporter'];
var running=false,lastReport=null;
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function reportHtml(r){
  var rows=Object.keys(r.summary).map(function(k){return '<tr><th>'+esc(k)+'</th><td>'+esc(r.summary[k])+'</td></tr>'}).join('');
  var steps=r.timeline.map(function(s){return '<li><b>'+esc(s.agent)+'</b> <code>'+esc(s.tool)+'</code><br>'+esc(s.text)+'</li>'}).join('');
  return '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Incident report</title><style>body{font:16px/1.6 system-ui,sans-serif;max-width:760px;margin:40px auto;padding:0 20px;color:#111}th{text-align:left;padding:6px 16px 6px 0;vertical-align:top;color:#555}code{background:#eee;padding:1px 5px;border-radius:4px}li{margin:10px 0}footer{margin-top:40px;color:#666;font-size:.85rem}</style></head><body><h1>Incident report: '+esc(r.scenario)+'</h1><table>'+rows+'</table><h2>Agent timeline</h2><ol>'+steps+'</ol><footer>Generated by Sentinel-X (demo, dry-run mode). Designed and developed by Nikhil Chary Sriramoju.</footer></body></html>';
}
function init(){
  var tl=SX.$('#timeline');if(!tl)return;
  var chips=SX.$('#agentChips'),gate=SX.$('#gate'),rep=SX.$('#report'),cbs={};
  AGENTS.forEach(function(a){var s=document.createElement('span');s.className='agent';s.textContent=a;chips.appendChild(s);cbs[a]=s});
  Object.keys(SCEN).forEach(function(k){var b=document.createElement('button');b.className='btn small';b.textContent=SCEN[k].name;b.dataset.k=k;SX.$('#scen').appendChild(b);SX.commands.push({label:'Run incident: '+SCEN[k].name,hint:'Agents',run:function(){SX.goto('#agents');play(k)}})});
  SX.$('#scen').addEventListener('click',function(e){var k=e.target.dataset&&e.target.dataset.k;if(k&&!running)play(k)});
  function setActive(a){AGENTS.forEach(function(n){var c=cbs[n];c.classList.remove('on');if(AGENTS.indexOf(n)<AGENTS.indexOf(a))c.classList.add('done')});cbs[a].classList.add('on');cbs[a].classList.remove('done')}
  function add(agent,tool,text){
    var li=document.createElement('li');li.className='step';
    var w=document.createElement('span');w.className='who';w.textContent=agent;var d=document.createElement('div');
    var c=document.createElement('code');c.textContent=tool;var p=document.createElement('p');p.textContent=text;d.append(c,p);li.append(w,d);tl.appendChild(li);
    lastReport.timeline.push({agent:agent,tool:tool,text:text});
  }
  function ask(text){
    return new Promise(function(res){
      SX.$('#gateText').textContent=text;gate.hidden=false;
      var ok=SX.$('#approve'),no=SX.$('#deny');
      function done(v){ok.onclick=no.onclick=null;gate.hidden=true;res(v)}
      ok.onclick=function(){done(true)};no.onclick=function(){done(false)};ok.focus({preventScroll:true});
    });
  }
  async function play(k){
    if(running)return;running=true;var sc=SCEN[k],t0=performance.now();
    lastReport={scenario:sc.name,timeline:[],summary:{}};
    SX.$$('#scen button').forEach(function(b){b.disabled=true});tl.replaceChildren();rep.hidden=true;gate.hidden=true;AGENTS.forEach(function(n){cbs[n].className='agent'});
    var gap=SX.reduce?150:750;
    setActive('Monitor');add('Monitor','ingest.alert()',sc.alert+'. Severity: '+sc.sev+'.');await SX.sleep(gap);
    setActive('Planner');add('Planner','plan.create()','Enrich with threat intelligence, inspect any file with the CNN, score the risk, propose containment, then write the report.');await SX.sleep(gap);
    setActive('Analyst');var hit=SX.rag.top(sc.q);
    add('Analyst','rag.retrieve("'+sc.q+'")','Best source: '+hit.id+' '+hit.title+' (similarity '+hit.score.toFixed(2)+').');await SX.sleep(gap);
    var cn=null,V=SX.vision;
    if(sc.cnn){cn=V.cnnScan(sc.cnn);add('Analyst','vision.scan("'+sc.file+'")',V.KNAME[cn.top]+' at '+Math.round(cn.conf*100)+'% confidence.')}
    else add('Analyst','vision.scan()','Skipped. This event has no file to inspect.');
    await SX.sleep(gap);
    setActive('Reasoner');var risk=Math.min(99,Math.round(sc.base+(cn?18*cn.conf:0)+10*Math.min(1,hit.score*2)));
    var band=risk>=80?'critical':risk>=60?'high':'medium';
    add('Reasoner','llm.reason(evidence)','Risk '+risk+' of 100 ('+band+'). '+sc.sum+' Mapped to MITRE ATT&CK '+sc.mitre+'.');await SX.sleep(gap);
    setActive('Responder');add('Responder','policy.propose()','Proposed actions: '+sc.actions.join('; ')+'.');
    var go=true;
    if(SX.$('#hitl').checked){go=await ask('Approve these '+sc.actions.length+' containment actions?')}
    if(go){await SX.sleep(gap/2);add('Responder','actions.execute(dry_run=true)','Executed in dry-run: '+sc.actions.length+' actions completed.')}
    else add('Responder','actions.skip()','Declined by the analyst. Escalated for manual handling.');
    await SX.sleep(gap);
    setActive('Reporter');add('Reporter','report.write()','Incident report generated.');cbs.Reporter.classList.remove('on');cbs.Reporter.classList.add('done');
    SX.mitre.hit(sc.mitre,2);
    lastReport.summary={'Severity':band+' (risk '+risk+' of 100)','MITRE ATT&CK':sc.mitre+' ('+hit.title+')','CNN finding':cn?V.KNAME[cn.top]+' ('+Math.round(cn.conf*100)+'%) on '+sc.file:'Not applicable','Knowledge source':hit.id+' at similarity '+hit.score.toFixed(2),'Response':go?sc.actions.join('. '):'None taken. Awaiting an analyst.','Demo triage time':((performance.now()-t0)/1000).toFixed(1)+' s (includes any wait for your approval)'};
    lastReport.generated=new Date().toISOString();
    rep.replaceChildren();var h=document.createElement('h4');h.textContent='Incident report: '+sc.name;var dl=document.createElement('dl');
    Object.keys(lastReport.summary).forEach(function(key){var a=document.createElement('dt');a.textContent=key;var b=document.createElement('dd');b.textContent=lastReport.summary[key];dl.append(a,b)});
    var btns=document.createElement('div');btns.className='row-btns no-print';
    var j=document.createElement('button');j.className='btn small';j.textContent='Download JSON';j.onclick=function(){SX.download('incident-report.json',JSON.stringify(lastReport,null,2),'application/json')};
    var hh=document.createElement('button');hh.className='btn small';hh.textContent='Download printable report';hh.onclick=function(){SX.download('incident-report.html',reportHtml(lastReport),'text/html')};
    btns.append(j,hh);rep.append(h,dl,btns);rep.hidden=false;
    SX.$$('#scen button').forEach(function(b){b.disabled=false});running=false;
  }
  SX.agents={play:play,keys:Object.keys(SCEN)};
}
SX.inits.push(init);
})();
